---
- name: Disable swap
  command: swapoff -a

- name: Include "{{ansible_os_family}}" Kubernetes recipe
  include_tasks: "{{ansible_os_family}}.yaml"

- name: Include "{{kube_type_of_node}}" tasks
  include_tasks: "{{kube_type_of_node}}.yaml"

